# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /recycle  #项目路径名
# 应用名称
spring:
  application:
    name: recycle-boot



  #数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recycle_app?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

  #静态资源
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # type-aliases-package:   # 所有Entity别名类所在包